name: nathanandlauren
version: 0.0.1
description: >
  A simple wedding site and blog for
  Nathan and Lauren Evans
homepage: http://nathanandlauren.com
dependencies:
  browser: '>=0.9.0 <0.11.0'
  react: 0.8.7
transformers:
- $dart2js:
    minify: true
    sourceMaps: false
    suppressHints: true
    suppressWarnings: true